<?php

//Step 1: do not forget to enable sessions first!

session_start();
?>
<html><head><title>PHP Captcha Demo</title></head>
<body>
    <?php
    if(!isset($_POST['captchatext']) || !isset($_SESSION['phpcaptcha'])) {
    
        // Step 2: reference the captcha as image and create form -->
    
        ?>
        <p>Image:</p>
        <p><img src="../index.php" alt="Captcha" title="Captcha"/></p>
        <form name="check" method="post" action="index.php">
            <p>
                Type text from image above:
            </p>
            <p>
                <input type="text" name="captchatext" value="">
            </p>
            <p>
                <input type="submit">
            </p>
        </form>
    <?php
    } else {
    
        // Step 3: evaluate the posted text by user against the session variable generated by the captcha
    
        if($_POST['captchatext'] == $_SESSION['phpcaptcha']) {
            $hint='Captcha <b>solved</b>!';
        } else {
            $hint='Captcha NOT solved! Image was asking for <b>'.$_SESSION['phpcaptcha'].'</b> but <b>'.$_POST['captchatext'].'</b> given by user';
        }
        echo '<p>'.$hint.'</p>';
        echo '<a href="index.php">Restart demo</a>';
    }
    ?>
</body>
</html>
